# Generated by Django 3.2.14 on 2024-04-07 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionID', models.CharField(blank=True, max_length=255, null=True)),
                ('SectionName', models.CharField(blank=True, max_length=255, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChatQuestion', models.CharField(blank=True, max_length=255, null=True)),
                ('ChatResponse', models.CharField(blank=True, max_length=255, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('SectionID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sectionhistory')),
            ],
        ),
    ]
